### PR TITLE
Make reconstructed rhoE more stable

### LINKED ISSUE #2602: wall function flate plate compressibleSST case result wrong
Describe the bug
When running the compressible SST case located in TestCases/wallFunctions/FlatPlate/compressible_SST, the output results are clearly incorrect. Additionally, the simulation crashes with the error shown in the attached screenshot.

Warning: y+ < 5 in 1 points, for which the wall model is not active.

I suspect the error may be triggered by a node shared between the symmetry boundary and the wall boundary. However, even before the crash, the contour results (e.g., velocity, temperature, or turbulence fields) are visibly unphysical, suggesting that the entire wall function module may contain additional bugs beyond this boundary issue.

To Reproduce

Navigate to: TestCases/wallFunctions/FlatPlate/compressible_SST
Run: SU2_CFD config.cfg
Observe:

Program terminates with the error shown in the screenshot
Prior to crash, inspect solution output — results deviate significantly from expected flat plate behavior

Expected behavior

The case should complete without errors
Skin friction, heat transfer, and flow profiles should align with compressible turbulent flat plate theory (e.g., Nichols & Nelson 2004, or standard log-law validation)

Thank You

### PR DESCRIPTION
**Pull request by pcarruscag**
## Proposed Changes
Nijso found that the "load less stuff" PR was causing the compressible wall function case to diverge.
The problem, and fix, are explained in the code change.

## Related Work
closes #2602

### CODE REVIEW

File: SU2_CFD/include/numerics_simd/flow/convection/common.hpp [hunk 1]
```diff
@@ -229,12 +229,20 @@ FORCEINLINE CPair<ReconVarType> reconstructPrimitives(Int iEdge, Int iPoint, Int
       musclPointLimited<nVarGrad>(iPoint, jPoint, vector_ij, limiters, gradients, V, kappa, relax);
       break;
     }
+    /*--- Recompute density using the reconstructed pressure and temperature. ---*/
     V.i.density() = V.i.pressure() / (gasConst * V.i.temperature());
     V.j.density() = V.j.pressure() / (gasConst * V.j.temperature());
 
+    /*--- Reconstruct enthalpy using dH/dT = Cp and dH/dv = v. Recomputing enthalpy would cause
+     * stability issues because we use rho E = rho H - P, which loses its relation to temperaure
```
Comment (bigfooted) [inline SU2_CFD/include/numerics_simd/flow/convection/common.hpp]:
```suggestion
     * stability issues because we use rho E = rho H - P, which loses its relation to temperature
```

**Review by bigfooted — APPROVED** [review]
Flatplate works again with MUSCL + CFL=400

File: TestCases/hybrid_regression.py [hunk 2]
```diff
@@ -224,15 +224,15 @@ def main():
...
+    turb_naca0012_sst_fixedvalues.test_vals = [-5.192389, -10.445226, 0.774100, 1.022534, 0.040529, -2.383436]
     test_list.append(turb_naca0012_sst_fixedvalues)
 
     # NACA0012 (SST, explicit Euler for flow and turbulence equations)
     turb_naca0012_sst_expliciteuler           = TestCase('turb_naca0012_sst_expliciteuler')
     turb_naca0012_sst_expliciteuler.cfg_dir   = "rans/naca0012"
     turb_naca0012_sst_expliciteuler.cfg_file  = "turb_NACA0012_sst_expliciteuler.cfg"
     turb_naca0012_sst_expliciteuler.test_iter = 10
-    turb_naca0012_sst_expliciteuler.test_vals = [-3.533766, -3.157224, 3.743381, 1.124757, 0.501700, -float("inf")]
+    turb_naca0012_sst_expliciteuler.test_vals = [-3.532365, -3.157224, 3.743381, 1.124798, 0.501715, -inf]
```
Comment (pcarruscag) [inline TestCases/hybrid_regression.py]:
```suggestion
    turb_naca0012_sst_expliciteuler.test_vals = [-3.532365, -3.157224, 3.743381, 1.124798, 0.501715, -float("inf")]
```

File: TestCases/parallel_regression.py [hunk 3]
```diff
@@ -498,7 +498,7 @@ def main():
     turb_naca0012_sst_expliciteuler.cfg_dir   = "rans/naca0012"
     turb_naca0012_sst_expliciteuler.cfg_file  = "turb_NACA0012_sst_expliciteuler.cfg"
     turb_naca0012_sst_expliciteuler.test_iter = 10
-    turb_naca0012_sst_expliciteuler.test_vals = [-3.533766, -3.157224, 3.743381, 1.124757, 0.501700, -float("inf")]
+    turb_naca0012_sst_expliciteuler.test_vals = [-3.532365, -3.157224, 3.743381, 1.124798, 0.501715, -inf]
```
Comment (pcarruscag) [inline TestCases/parallel_regression.py]:
```suggestion
    turb_naca0012_sst_expliciteuler.test_vals = [-3.532365, -3.157224, 3.743381, 1.124798, 0.501715, -float("inf")]
```
