### PR TITLE
Fix #1667 Potential crash for the OpenMP multi-thread running.

### LINKED ISSUE #1667: Potential crash for the OpenMP multi-thread running
A crash may occur when the number of threads is larger than the number of points in OpenMP mode. For example, a boundary condition marker has a few edge elements, and the model runs on a 10-core CPU (20 threads).  

One of the crash places is at 
`
    InverseDiagonalBlock_ILUMatrix(end-1, &invM[(end-1)*nVar*nVar]);
`
The value `end-1` could be a random value due to the skipped value assignment in vector `omp_partitions`. 

It seems that the logic for setting and using `omp_partitions` needs to be revised. The reproducing script is provided. 

Win11 + VS2022
SU2 7.3.1

[omp_crash_su2.cfg.txt](https://github.com/su2code/SU2/files/8905694/omp_crash_su2.cfg.txt)
[mesh.su2.txt](https://github.com/su2code/SU2/files/8905687/mesh.su2.txt)

### PR DESCRIPTION
**Pull request by lcheng9**
## Proposed Changes
Initialize the omp_partitions vector with the number of points, skip the for loop if the last partition has been calculated. A light-weight checker is added also to verify the partition vector, promote a warning or error message if necessary.
 

## Related Work
Fix #1667 Potential crash for the OpenMP multi-thread running.

## PR Checklist
*Put an X by all that apply. You can fill this out after submitting the PR. If you have any questions, don't hesitate to ask! We want to help. These are a guide for you to know what the reviewers will be looking for in your contribution.*

- [x] I am submitting my contribution to the develop branch.
- [x] My contribution generates no new compiler warnings (try with the '-Wall -Wextra -Wno-unused-parameter -Wno-empty-body' compiler flags, or simply --warnlevel=2 when using meson).
- [x] My contribution is commented and consistent with SU2 style.
- [ ] I have added a test case that demonstrates my contribution, if necessary.
- [ ] I have updated appropriate documentation (Tutorials, Docs Page, config_template.cpp) , if necessary.

### CODE REVIEW

File: Common/src/linear_algebra/CSysMatrix.cpp [hunk 1]
```diff
@@ -202,7 +203,17 @@ void CSysMatrix<ScalarType>::Initialize(unsigned long npoint, unsigned long npoi
...
+
+  for (unsigned long thread = 0; thread < omp_num_parts; ++thread) {
+    const unsigned long begin = omp_partitions[thread];
+    const unsigned long end = omp_partitions[thread + 1];
+    if (begin > end) {
+      SU2_MPI::Error("Invalid nodes are distributed in the thread " + to_string(thread) + ".", CURRENT_FUNCTION);
+    } else if (begin == end) {
+      cout << "WARNING: Redundent thread has been detected. Performance could be impacted." << endl;
+      break;
+    }
```
Comment (pcarruscag) [inline Common/src/linear_algebra/CSysMatrix.cpp:215]: I think it is impossible for begin > end give the way they are computed now.
```suggestion
    const auto begin = omp_partitions[thread];
    const auto end = omp_partitions[thread + 1];
    if (begin == end) {
      cout << "WARNING: Redundant thread has been detected. Performance could be impacted due to low number of nodes per thread." << endl;
      break;
    }
```

**Review by pcarruscag — APPROVED** [review]

**Comment by pcarruscag** [comment]
Thank you for opening a PR, please add yourself to AUTHORS.md (note that it is in a funny alphabetical order with upper case before lower case)

**Comment by pcarruscag** [comment]
Thank you for opening a PR, please add yourself to AUTHORS.md (note that it is in a funny alphabetical order with upper case before lower case)

**Comment by lcheng9** [comment]
Thanks for the approval. I will update the AUTHORS.md next time together with other changes.

**Review by WallyMaier — APPROVED** [review]
