### PR TITLE
Fix calculation of number of spanwise sections

### LINKED ISSUE #1219: MPI fatal error when using more than 6 processors at Turbomachinery Preprocessing step
**### MPI partitioning issues for Turbomachinery for processor count more than 6 in mpi**

I have noticed an issue with running my turbomachinery model in SU2 version 7.04, 7.1 and version 7.1.1 during the Turbomachinery preprocessing step at the  "Initialize Turbo Vertex Structure" where it **incorrectly** calculates the number of spanwise section in zone 0 and then there is a MPI fatal error. **This happens only when I use more than 6 processors**. For less than or equal to 6 processors there is no error. I have this issue with 7.04, 7.1 and now 7.1.1. 

This issue has a previous bug report in the MPI partitioning issues for Turbomachinery runs #990

I am sure the config file is correct. I have my solutions from 6 processors, but I really need to scale up the processor count so that the restitution time is within a reasonable time.
Below is an example of where it crashes for 7 processors: 
### WITH 7 processors:
---------------------- Turbomachinery Preprocessing ---------------------

Initialize Turbo Vertex Structure.
**_Number of span-wise sections in Zone 0: 139. [This is incorrect number of span-wise sections]_**
Max number of span-wise sections among all zones: 139.
Initialize solver containers for average and performance quantities.
Compute inflow and outflow average geometric quantities.
[1:node0567] unexpected disconnect completion event from [0:node0564]
[3:node0566] unexpected disconnect completion event from [0:node0564]

### WITH 6 processors:
Initialize Turbo Vertex Structure.
**Number of span-wise sections in Zone 0: 137.  [This is the correct number of span-wise sections]**
Max number of span-wise sections among all zones: 137.
Initialize solver containers for average and performance quantities.
Compute inflow and outflow average geometric quantities.
Transfer average geometric quantities to zone 0.
Inlet area for Row 1: 30.7045 cm^2.
Oulet area for Row 1: 16.9716 cm^2.
Recomputed number of blades for Row 1: 36.
Initialize inflow and outflow average solution quantities.
Inlet flow angle for Row 1: -0.00422866°.
Outlet flow angle for Row 1: -28.9224°.
------------------------------ Begin Solver -----------------------------
.......

System settings:
**CLUSTER**
 - OS: CentOS release 6.5
 - C++ compiler and version: GCC/7.3.0-2.30
 - MPI implementation and version: compiler/intel/2018.0.1 intelmpi/2018.0.1/64 mkl/2018.0.1
 - SU2 Version: [v7.1 and 7.1.1]
Thanks
Ashvin

### PR DESCRIPTION
**Pull request by pcarruscag**
## Proposed Changes
Try to fix #1219 based on Stephan's insight in #990

## PR Checklist
- [X] I am submitting my contribution to the develop branch.
- [X] My contribution generates no new compiler warnings (try with the '-Wall -Wextra -Wno-unused-parameter -Wno-empty-body' compiler flags, or simply --warnlevel=2 when using meson).
- [X] My contribution is commented and consistent with SU2 style.
- [X] I have added a test case that demonstrates my contribution, if necessary.
- [X] I have updated appropriate documentation (Tutorials, Docs Page, config_template.cpp) , if necessary.

### CODE REVIEW

**Review by TobiKattmann — APPROVED** [review]
Nice investigative work 🕵️ with the issues 👍

File: Common/src/geometry/CPhysicalGeometry.cpp [hunk 1]
```diff
@@ -5108,53 +5102,56 @@ unsigned short iMarker, jMarker, iMarkerTP, iSpan, jSpan, kSpan = 0;
...
+              if (!nodes->GetDomain(iPoint)) continue;
+
+              PeriodicBoundary = config->GetMarker_All_PerBound(jMarker);
+              jVertex = nodes->GetVertex(iPoint, jMarker);
+
+              if ((jVertex != -1) && (PeriodicBoundary == (val_iZone + 1))){
+                coord = nodes->GetCoord(iPoint);
+                radius = sqrt(coord[0]*coord[0]+coord[1]*coord[1]);
+                switch (config->GetKind_TurboMachinery(val_iZone)){
+                case CENTRIFUGAL:
```
Comment (TobiKattmann) [inline Common/src/geometry/CPhysicalGeometry.cpp:5128]: `[...] as I will not debug that function any further because it has the world record for nested loops.`
@pcarruscag, 2021-03-04, Digital ink on computerscreen in #1219

Comment (TobiKattmann) [reply Common/src/geometry/CPhysicalGeometry.cpp:5128]: Continue-man to the rescue 🦸

File: Common/src/geometry/CPhysicalGeometry.cpp [hunk 2]
```diff
@@ -5192,46 +5178,15 @@ unsigned short iMarker, jMarker, iMarkerTP, iSpan, jSpan, kSpan = 0;
...
-      //
-      //  for (iSpan = 0; iSpan < nSpan; iSpan++){
-      //    if(rank == MASTER_NODE){
-      //      cout << setprecision(16)<<  iSpan +1 << " with a value of " <<valueSpan[iSpan]<< " at flag " << marker_flag <<endl;
-      //    }
-      //  }
+      /*--- Terrible stuff to do but so is this entire bloody function goodness me... ---*/
+      SpanWiseValue[marker_flag -1] = valueSpan;
 
+      sort(SpanWiseValue[marker_flag -1], SpanWiseValue[marker_flag -1]+nSpan);
```
Comment (TobiKattmann) [inline Common/src/geometry/CPhysicalGeometry.cpp:5186]: 👍

File: Common/src/geometry/CPhysicalGeometry.cpp (hunk 1 above)
Comment (TobiKattmann) [reply Common/src/geometry/CPhysicalGeometry.cpp:5128]: Info: The artist has yet to name his piece 🎨

Comment (pcarruscag) [reply Common/src/geometry/CPhysicalGeometry.cpp:5128]: Proper thing to do would be to find the vertices this function wants to then not repeat all those conditions 3 times... But anyway, I scrolled down from this function and realized this was only a drop in the ocean.

File: Common/src/geometry/CPhysicalGeometry.cpp (hunk 2 above)
Comment (pcarruscag) [reply Common/src/geometry/CPhysicalGeometry.cpp:5186]: I should hope they fire anyone who implements sort "inline" especially the quadratic complexity variant.
I also hope the comment was correct because I did not try to understand if this "sort" had something different about it.
