### PR TITLE
Optimization of multigrid settings

### LINKED ISSUE #1549: restart for multigrid not correct for turbulence
**Describe the bug**
a primal and adjoint restart with multigrid will not produce the correct residuals for turbulence.

**To Reproduce**
Use the restart validation tutorial for species transport. Switch off Species transport and put turbulence model to SST or SA to see different residuals for the turbulence quantities
[species tutorial](https://su2code.github.io/tutorials/Species_Transport/)

**Desktop (please complete the following information):**
 - OS: linux
 - C++ compiler and version: gcc 5.3.0
 - MPI implementation and version: OpenMPI 3.1.6
 - SU2 Version: current develop

### PR DESCRIPTION
**Pull request by bigfooted**
## Proposed Changes
*Give a brief overview of your contribution here in a few sentences.*

This PR is an improvement of the multigrid method. The goal is to make it more robust and less sensitive to user-defined settings. 
It introduces the following:
1. When the smoother converges sufficiently, we stop the smoothing and exit the smoother.
This means that the option:
```
MG_PRE_SMOOTH= ( 5, 5, 5, 5, 5 )
MG_POST_SMOOTH= ( 5, 5, 5, 5, 5 )
```
effectively becomes the maximum number of iterations that are being performed. The smoothing threshold is given by:
`MG_SMOOTH_RES_THRESHOLD=0.5`
You can still turn it off using:
`MG_SMOOTH_EARLY_EXIT= YES`

2. The damping factors are adaptive. When the smoother converges (exits) within the given number of maximum iterations, the damping factors are increased. When the smoother residuals are larger than the starting residuals, we decrease the damping factor. This means that the option:
```
MG_DAMP_RESTRICTION= 0.5
MG_DAMP_PROLONGATION= 0.5
```
effectively becomes a starting damping factor. 

3. Limit the number of MG meshes such that the smallest and coarsest mesh always has more than MG_MIN_MESHSIZE  points. This means that the option 
`MGLEVEL=4`
effectively becomes a maximum number of MG levels.

4. We also expose the smoothing coefficient for correction smoothing to the user:
`MG_SMOOTH_COEFF=1.25`
 
5. fixes multigrid restarts for turbulence problems.

## Related Work
*Resolve any issues (bug fix or feature request), note any related PRs, or mention interactions with the work of others, if any.*
A follow-up to #2712 

Will fix #1549 

## PR Checklist
*Put an X by all that apply. You can fill this out after submitting the PR. If you have any questions, don't hesitate to ask! We want to help. These are a guide for you to know what the reviewers will be looking for in your contribution.*

- [x] I am submitting my contribution to the develop branch.
- [x] My contribution generates no new compiler warnings (try with --warnlevel=3 when using meson).
- [x] My contribution is commented and consistent with SU2 style (https://su2code.github.io/docs_v7/Style-Guide/).
- [x] I used the pre-commit hook to prevent dirty commits and used `pre-commit run --all` to format old commits.
- [x] I have added a test case that demonstrates my contribution, if necessary.
- [ ] I have updated appropriate documentation (Tutorials, Docs Page, config_template.cpp), if necessary.

### CODE REVIEW

File: Common/include/CConfig.hpp [hunk 1]
```diff
@@ -3876,6 +3882,37 @@ class CConfig {
...
+  /*!
+   * \brief Minimum number of CVs on the coarsest multigrid level.
+   */
+  unsigned long GetMG_Min_MeshSize() const { return MG_Min_MeshSize; }
+
+  /*!
+   * \brief Whether implicit-lines agglomeration from walls is enabled.
+   */
+  bool GetMG_Implicit_Lines() const { return MG_Implicit_Lines; }
+
```
Comment (pcarruscag) [inline Common/include/CConfig.hpp]: Make a struct for the group of MG settings please

File: Common/src/geometry/CMultiGridGeometry.cpp [hunk 2]
```diff
@@ -1289,3 +1282,237 @@ su2double CMultiGridGeometry::ComputeLocalCurvature(const CGeometry* fine_grid,
...
+          if (fine_grid->nodes->GetBoundary(jPoint)) continue;
+          if (fine_grid->nodes->GetAgglomerate(jPoint)) continue;
+
+          /*--- Compute normalized direction to candidate ---*/
+          su2double vec[MAXNDIM] = {0.0};
+          su2double len2 = 0.0;
+          for (unsigned short d = 0; d < nDim; ++d) {
+            vec[d] = fine_grid->nodes->GetCoord(jPoint, d) - fine_grid->nodes->GetCoord(current, d);
+            len2 += vec[d] * vec[d];
+          }
```
Comment (pcarruscag) [inline Common/src/geometry/CMultiGridGeometry.cpp]: There is a distance function

File: Common/src/geometry/CMultiGridGeometry.cpp [hunk 3]
```diff
@@ -1289,3 +1282,237 @@ su2double CMultiGridGeometry::ComputeLocalCurvature(const CGeometry* fine_grid,
...
+          if (len2 <= 0.0) continue;
+          const su2double len = sqrt(len2);
+          for (unsigned short d = 0; d < nDim; ++d) vec[d] /= len;
+
+          /*--- Alignment with previous direction ---*/
+          su2double dot = 0.0;
+          for (unsigned short d = 0; d < nDim; ++d) dot += vec[d] * prev_dir[d];
```
Comment (pcarruscag) [inline Common/src/geometry/CMultiGridGeometry.cpp]: Tell Claude about GeometryToolbox please

File: SU2_CFD/src/integration/ComputeLinSysResRMS.hpp [hunk 4]
```diff
@@ -0,0 +1,60 @@
...
+
+  su2double globalSum = 0.0;
+  SU2_MPI::Allreduce(&localSum, &globalSum, 1, MPI_DOUBLE, MPI_SUM, SU2_MPI::GetComm());
+
+  unsigned long globalNPointDomain = 0;
+  SU2_MPI::Allreduce(&nPointDomain, &globalNPointDomain, 1, MPI_UNSIGNED_LONG, MPI_SUM, SU2_MPI::GetComm());
+
+  if (globalNPointDomain == 0) return 0.0;
+  return std::sqrt(globalSum / (static_cast<su2double>(globalNPointDomain) * nVar));
+}
```
Comment (pcarruscag) [inline SU2_CFD/src/integration/ComputeLinSysResRMS.hpp]: LinSysRes is a CSysVector and it has a norm function

File: SU2_CFD/src/integration/CMultiGridIntegration.cpp [hunk 5]
```diff
@@ -28,6 +28,109 @@
...
+    for (unsigned short v = 0; v < nVar; ++v)
+      localSum += res[v] * res[v];
+  }
+  su2double globalSum = 0.0;
+  unsigned long globalNPoint = 0;
+  SU2_MPI::Allreduce(&localSum, &globalSum, 1, MPI_DOUBLE, MPI_SUM, SU2_MPI::GetComm());
+  SU2_MPI::Allreduce(&nPointDomain, &globalNPoint, 1, MPI_UNSIGNED_LONG, MPI_SUM, SU2_MPI::GetComm());
+  if (globalNPoint == 0) return 0.0;
+  return sqrt(globalSum / static_cast<su2double>(globalNPoint * nVar));
+}
```
Comment (pcarruscag) [inline SU2_CFD/src/integration/CMultiGridIntegration.cpp]:
```suggestion
```

File: SU2_CFD/src/integration/CMultiGridIntegration.cpp [hunk 6]
```diff
@@ -28,6 +28,109 @@
...
+    /*--- Scale-up signal: requires early exit on every level.
+     *    Making progress at max iters is good, but the damping is already doing useful work;
+     *    do not increase it further until the smoother actually exits early. ---*/
+    if (hit_max) local_all_early = 0;
+  }
+  if (local_inspected == 0) return;
+
+  int global_any_stagnant = local_any_stagnant;
+  int global_all_early    = local_all_early;
+#ifdef HAVE_MPI
```
Comment (pcarruscag) [inline SU2_CFD/src/integration/CMultiGridIntegration.cpp]: not needed

File: SU2_CFD/src/integration/CMultiGridIntegration.cpp [hunk 7]
```diff
@@ -257,6 +379,57 @@ void CMultiGridIntegration::MultiGrid_Iteration(CGeometry ****geometry,
...
+                 [&](unsigned short i){ return config[iZone]->GetMG_PostSmooth(i); },
+                 lastPostSmoothRMS, nMGLevels - 1);
+        printRow("Corr.-smooth: ", lastCorrecSmoothIters,
+                 [&](unsigned short i){ return config[iZone]->GetMG_CorrecSmooth(i); },
+                 lastCorrecSmoothRMS, nMGLevels - 1);
+        cout << fixed << setprecision(4)
+             << "Damp. (restr/prolong): " << config[iZone]->GetDamp_Res_Restric()
+             << " / " << config[iZone]->GetDamp_Correc_Prolong() << "\n";
+        cout << defaultfloat << setprecision(6);
+      }
```
Comment (pcarruscag) [inline SU2_CFD/src/integration/CMultiGridIntegration.cpp:436]: Can you use the table writer please?

File: SU2_CFD/src/integration/CMultiGridIntegration.cpp [hunk 8]
```diff
@@ -425,13 +602,53 @@ void CMultiGridIntegration::PreSmoothing(unsigned short RunTime_EqSystem,
       /*--- Space integration ---*/
       Space_Integration(geometry_fine, solver_container_fine, numerics_fine, config, iMesh, iRKStep, RunTime_EqSystem);
 
+      /*--- Capture initial RMS after the very first residual evaluation.
+       *    This is the earliest point where LinSysRes = R(u_current) (not stale). ---*/
+      if (iPreSmooth == 0 && iRKStep == 0) {
+        BEGIN_SU2_OMP_SAFE_GLOBAL_ACCESS
+        {
+          lastPreSmoothRMS[iMesh][0] = ComputeLinSysResRMS(solver_fine, geometry_fine);
```
Comment (pcarruscag) [inline SU2_CFD/src/integration/CMultiGridIntegration.cpp]: Don't compute residuals without threads

File: SU2_CFD/src/integration/CMultiGridIntegration.cpp [hunk 9]
```diff
@@ -402,8 +575,12 @@ void CMultiGridIntegration::PreSmoothing(unsigned short RunTime_EqSystem,
   const bool classical_rk4 = (config->GetKind_TimeIntScheme() == CLASSICAL_RK4_EXPLICIT);
   const unsigned short nPreSmooth = config->GetMG_PreSmooth(iMesh);
   const unsigned long timeIter = config->GetTimeIter();
+  const bool early_exit = config->GetMG_Smooth_EarlyExit() && (nPreSmooth > 1);
 
-  /*--- Do a presmoothing on the grid iMesh to be restricted to the grid iMesh+1 ---*/
+  /*--- Reset the shared early-exit flag (master only). ---*/
+  BEGIN_SU2_OMP_SAFE_GLOBAL_ACCESS
+  { mg_early_exit_flag = false; }
+  END_SU2_OMP_SAFE_GLOBAL_ACCESS
```
Comment (pcarruscag) [inline SU2_CFD/src/integration/CMultiGridIntegration.cpp]:
```suggestion
  SU2_OMP_SAFE_GLOBAL_ACCESS(mg_early_exit_flag = false;)
```

File: SU2_CFD/src/integration/CMultiGridIntegration.cpp [hunk 10]
```diff
@@ -425,13 +602,53 @@ void CMultiGridIntegration::PreSmoothing(unsigned short RunTime_EqSystem,
...
+    }
+  }
+
+  /*--- Record final RMS, progress flag, and (for early-exit path) re-use already-computed value. ---*/
+  BEGIN_SU2_OMP_SAFE_GLOBAL_ACCESS
+  {
+    if (early_exit && mg_early_exit_flag) {
+      /*--- Early exit: RMS threshold was met; the RMS that triggered exit is current_rms
+       *    but we don't store it — just do a final read for the output. ---*/
+      lastPreSmoothRMS[iMesh][1] = ComputeLinSysResRMS(solver_fine, geometry_fine);
```
Comment (pcarruscag) [inline SU2_CFD/src/integration/CMultiGridIntegration.cpp]: Actually, why do you need to recompute residuals? Aren't the solvers computing them already?

File: Common/include/CConfig.hpp (hunk 1 above)
Comment (bigfooted) [reply Common/include/CConfig.hpp]: I am also changing to enum class for ENUM_MG_CYCLE.

File: SU2_CFD/src/integration/CMultiGridIntegration.cpp (hunk 10 above)
Comment (bigfooted) [reply SU2_CFD/src/integration/CMultiGridIntegration.cpp]: getRes_RMS only has the fine grid values, this one computes it on all grid levels.

File: SU2_CFD/src/integration/CMultiGridIntegration.cpp (hunk 8 above)
Comment (bigfooted) [reply SU2_CFD/src/integration/CMultiGridIntegration.cpp]: ok, so computelinsysres outside of the omp loop?

File: SU2_CFD/src/integration/CMultiGridIntegration.cpp (hunk 7 above)
Comment (bigfooted) [reply SU2_CFD/src/integration/CMultiGridIntegration.cpp:436]: the one from printingtoolbox? sure.

File: Common/src/geometry/CMultiGridGeometry.cpp (hunk 2 above)
Comment (bigfooted) [reply Common/src/geometry/CMultiGridGeometry.cpp]: this one? GeometryToolbox::Distance

File: Common/include/CConfig.hpp [hunk 11]
```diff
@@ -3878,40 +3880,40 @@ class CConfig {
...
-    return MG_CorrecSmooth[val_mesh];
+    if (MGOptions.nMG_CorrecSmooth == 0) return 0;
+    return MGOptions.MG_CorrecSmooth[val_mesh];
   }
 
   /*!
    * \brief Whether early exit is enabled for MG smoothing iterations.
    */
-  bool GetMG_Smooth_EarlyExit() const { return MG_Smooth_EarlyExit; }
+  bool GetMG_Smooth_EarlyExit() const { return MGOptions.MG_Smooth_EarlyExit; }
```
Comment (pcarruscag) [inline Common/include/CConfig.hpp]: So the idea is to return a reference to the struct as well, replacing the individual accessors, so that there is just one clean interface for all MG settings.

File: Common/include/option_structure.hpp [hunk 12]
```diff
@@ -2281,17 +2281,17 @@ static const MapType<std::string, JUMP_DEFINITION> Jump_Map = {
...
-enum MG_CYCLE {
-  V_CYCLE = 0,        /*!< \brief V cycle. */
-  W_CYCLE = 1,        /*!< \brief W cycle. */
-  FULLMG_CYCLE = 2    /*!< \brief FullMG cycle. */
-};
-static const MapType<std::string, MG_CYCLE> MG_Cycle_Map = {
-  MakePair("V_CYCLE", V_CYCLE)
-  MakePair("W_CYCLE", W_CYCLE)
-  MakePair("FULLMG_CYCLE", FULLMG_CYCLE)
+enum class ENUM_MG_CYCLE {
```
Comment (pcarruscag) [inline Common/include/option_structure.hpp]: Just MG_CYCLE, and you can shorten the enum cases to just V, W, FULL since they are not defined globally anymore due to `enum class`.

File: Common/include/CConfig.hpp (hunk 11 above)
Comment (bigfooted) [reply Common/include/CConfig.hpp]: ok, so we get rid of the individual GetMG_* functions?

Comment (bigfooted) [reply Common/include/CConfig.hpp]: @pcarruscag  mmm, like this?
const CMGOptions& GetMGOptions() const { return MGOptions; }
and then we can do this for example:
config[iZone]->GetMGOptions().MG_Smooth_EarlyExit)

Comment (bigfooted) [reply Common/include/CConfig.hpp]: I looked at sstparsedoptions, and copying that instead, it then looks like this:
const auto& mgOptsZone = config[iZone]->GetMGOptions();
  if (mgOptsZone.MG_Smooth_EarlyExit) {

Comment (pcarruscag) [reply Common/include/CConfig.hpp]: yep

File: SU2_CFD/src/integration/CMultiGridIntegration.cpp [hunk 13]
```diff
@@ -243,6 +344,34 @@ void CMultiGridIntegration::MultiGrid_Iteration(CGeometry ****geometry,
   MultiGrid_Cycle(geometry, solver_container, numerics_container, config,
                   FinestMesh, RecursiveParam, RunTime_EqSystem, iZone, iInst);
 
+  /*--- Adapt coarse-grid CFL once per cycle using smoothing residuals gathered during the cycle.
+   *    lastPreSmoothRMS[iMesh+1][1] is the final RMS after pre-smoothing at the coarse level —
+   *    it is already MPI-reduced (computed via ComputeLinSysResRMS) and identical on all ranks.
+   *    This replaces the per-level Allreduce that was previously inside MultiGrid_Cycle. ---*/
+  {
```
Comment (pcarruscag) [inline SU2_CFD/src/integration/CMultiGridIntegration.cpp:341]: I don't think the extra scope is necessary
```suggestion
```

File: SU2_CFD/src/integration/CMultiGridIntegration.cpp [hunk 14]
```diff
@@ -208,19 +282,46 @@ void CMultiGridIntegration::MultiGrid_Iteration(CGeometry ****geometry,
...
+    const unsigned short nMGLevels = config[iZone]->GetnMGLevels();
+    const auto& mgOpts = config[iZone]->GetMGOptions();
+    for (unsigned short i = 0; i <= nMGLevels; ++i) {
+      lastPreSmoothIters[i]    = mgOpts.MG_PreSmooth[i];
+      lastPostSmoothIters[i]   = mgOpts.MG_PostSmooth[i];
+      lastCorrecSmoothIters[i] = mgOpts.MG_CorrecSmooth[i];
+      lastPreSmoothProgress[i]    = false;
+      lastPostSmoothProgress[i]    = false;
+      lastCorrecSmoothProgress[i] = false;
```
Comment (pcarruscag) [inline SU2_CFD/src/integration/CMultiGridIntegration.cpp]: Remove the "pretty" spaces, they're already out of line 😄

File: SU2_CFD/src/integration/CMultiGridIntegration.cpp [hunk 15]
```diff
@@ -625,14 +917,31 @@ void CMultiGridIntegration::SmoothProlongated_Correction(unsigned short RunTime_
...
   }
 
+  /*--- Record final correction norm for debugging output.
+   *    ComputeLinSysResRMS must be called by all threads (uses parallel dot). ---*/
+  {
+    const passivedouble final_corr_rms = ComputeLinSysResRMS(solver);
+    BEGIN_SU2_OMP_SAFE_GLOBAL_ACCESS
+    { lastCorrecSmoothRMS[iMesh][1] = final_corr_rms; }
+    END_SU2_OMP_SAFE_GLOBAL_ACCESS
+  }
```
Comment (pcarruscag) [inline SU2_CFD/src/integration/CMultiGridIntegration.cpp]: Use the one-line version.

File: subprojects/CoolProp
Comment (pcarruscag) [inline subprojects/CoolProp:1]: revert

File: SU2_CFD/include/integration/ComputeLinSysResRMS.hpp [hunk 16]
```diff
@@ -0,0 +1,63 @@
...
+ *       The return value is correct only on the master thread (thread 0).
+ *
+ * \param[in] solver - Solver whose LinSysRes is evaluated.
+ * \return Global RMS value (valid on master thread; other threads return 0).
+ */
+inline passivedouble ComputeLinSysResRMS(const CSolver* solver) {
+
+  /*--- squaredNorm() -> dot() uses OMP parallel for + barriers internally,
+   *    so all threads must participate. ---*/
+  const su2double sqNorm = solver->LinSysRes.squaredNorm();
```
Comment (pcarruscag) [inline SU2_CFD/include/integration/ComputeLinSysResRMS.hpp:48]: Did you answer the question about why you can't take these from the solver as we do in the NK solver, instead of recomputing?
Maybe I missed it.

Comment (bigfooted) [reply SU2_CFD/include/integration/ComputeLinSysResRMS.hpp:48]: We currently only have the norm available from linsysres on MESH_0. so we need to compute it. ComputeLinSysResRMS keeps the implementation compact.

File: SU2_CFD/src/integration/CMultiGridIntegration.cpp (hunk 15 above)
Comment (bigfooted) [reply SU2_CFD/src/integration/CMultiGridIntegration.cpp]: you mean remove the unneeded brackets or something else?
[edit] ok, there's also just OMP_SAFE_GLOBAL_ACCESS

File: Common/src/geometry/CMultiGridGeometry.cpp [hunk 17]
```diff
@@ -1289,3 +1276,234 @@ su2double CMultiGridGeometry::ComputeLocalCurvature(const CGeometry* fine_grid,
...
+        for (auto jPoint : fine_grid->nodes->GetPoints(current)) {
+          if (jPoint == current) continue;
+          if (!fine_grid->nodes->GetDomain(jPoint)) continue;
+          if (fine_grid->nodes->GetBoundary(jPoint)) continue;
+          if (fine_grid->nodes->GetAgglomerate(jPoint)) continue;
+
+          /*--- Compute normalized direction to candidate ---*/
+          su2double vec[MAXNDIM] = {0.0};
+          for (unsigned short d = 0; d < nDim; ++d)
+            vec[d] = fine_grid->nodes->GetCoord(jPoint, d) - fine_grid->nodes->GetCoord(current, d);
```
Comment (pcarruscag) [inline Common/src/geometry/CMultiGridGeometry.cpp]:
```suggestion
          GeometryToolbox::Distance(nDim, fine_grid->nodes->GetCoord(jPoint), fine_grid->nodes->GetCoord(current), vec);
```

File: Common/src/geometry/CMultiGridGeometry.cpp [hunk 18]
```diff
@@ -1289,3 +1276,234 @@ su2double CMultiGridGeometry::ComputeLocalCurvature(const CGeometry* fine_grid,
...
+          const su2double len =
+              GeometryToolbox::Distance(nDim, fine_grid->nodes->GetCoord(jPoint), fine_grid->nodes->GetCoord(current));
```
Comment (pcarruscag) [inline Common/src/geometry/CMultiGridGeometry.cpp]:
```suggestion
          const su2double len = GeometryToolbox::Norm(nDim, vec);
```

File: Common/src/geometry/CMultiGridGeometry.cpp [hunk 19]
```diff
@@ -1289,3 +1276,234 @@ su2double CMultiGridGeometry::ComputeLocalCurvature(const CGeometry* fine_grid,
...
+        L.push_back(best_neighbor);
+
+        /*--- Update direction for next step ---*/
+        su2double len2 = 0.0;
+        for (unsigned short d = 0; d < nDim; ++d) {
+          prev_dir[d] = fine_grid->nodes->GetCoord(best_neighbor, d) - fine_grid->nodes->GetCoord(current, d);
+          len2 += prev_dir[d] * prev_dir[d];
+        }
+        if (len2 <= 0.0) break;
+        const su2double len = sqrt(len2);
```
Comment (pcarruscag) [inline Common/src/geometry/CMultiGridGeometry.cpp]: Same as above

File: SU2_CFD/src/integration/CMultiGridIntegration.cpp [hunk 20]
```diff
@@ -444,9 +657,16 @@ void CMultiGridIntegration::PostSmoothing(unsigned short RunTime_EqSystem,
...
   const bool classical_rk4 = (config->GetKind_TimeIntScheme() == CLASSICAL_RK4_EXPLICIT);
-  const unsigned short nPostSmooth = config->GetMG_PostSmooth(iMesh);
+  const unsigned short nPostSmooth = mgOpts.MG_PostSmooth[iMesh];
   const unsigned long timeIter = config->GetTimeIter();
+  const bool early_exit = mgOpts.MG_Smooth_EarlyExit && (nPostSmooth > 1);
+
+  /*--- Reset the shared early-exit flag (master only). ---*/
+  BEGIN_SU2_OMP_SAFE_GLOBAL_ACCESS
+  { mg_early_exit_flag = false; }
+  END_SU2_OMP_SAFE_GLOBAL_ACCESS
```
Comment (pcarruscag) [inline SU2_CFD/src/integration/CMultiGridIntegration.cpp]:
```suggestion
  SU2_OMP_SAFE_GLOBAL_ACCESS(mg_early_exit_flag = false;)
```

File: SU2_CFD/src/integration/CMultiGridIntegration.cpp [hunk 21]
```diff
@@ -571,7 +837,17 @@ void CMultiGridIntegration::SmoothProlongated_Correction(unsigned short RunTime_
...
   END_SU2_OMP_FOR
 
-  /*--- Jacobi iterations. ---*/
+  /*--- Record initial correction norm for debugging output.
+   *    ComputeLinSysResRMS must be called by all threads (uses parallel dot). ---*/
+  {
+    const passivedouble initial_corr_rms = ComputeLinSysResRMS(solver);
+    BEGIN_SU2_OMP_SAFE_GLOBAL_ACCESS
+    { lastCorrecSmoothRMS[iMesh][0] = initial_corr_rms; }
+    END_SU2_OMP_SAFE_GLOBAL_ACCESS
```
Comment (pcarruscag) [inline SU2_CFD/src/integration/CMultiGridIntegration.cpp]:
``` suggestion
    SU2_OMP_SAFE_GLOBAL_ACCESS(lastCorrecSmoothRMS[iMesh][0] = initial_corr_rms;)
```

**Review by pcarruscag — APPROVED** [review]
