### PR TITLE
Fix MSW

### LINKED ISSUE #1161: Modified-Steger-Warming segfaults
I am making a note here that the MSW scheme in develop segfaults. I will try to find to fix the issue, unless someone already has.

### PR DESCRIPTION
**Pull request by pcarruscag**
## Proposed Changes
Leaks and stuff, @WallyMaier I did not check if the method is implemented correctly, looked decent on the naca0012.

## Related Work
fix #1161

## PR Checklist
- [X] I am submitting my contribution to the develop branch.
- [X] My contribution generates no new compiler warnings (try with the '-Wall -Wextra -Wno-unused-parameter -Wno-empty-body' compiler flags, or simply --warnlevel=2 when using meson).
- [X] My contribution is commented and consistent with SU2 style.
- [X] I have added a test case that demonstrates my contribution, if necessary.
- [X] I have updated appropriate documentation (Tutorials, Docs Page, config_template.cpp) , if necessary.

### CODE REVIEW

**Review by WallyMaier — APPROVED** [review]
@pcarruscag thanks for going through this! MSW is not definitely not the greatest scheme, but is used alot in hypersonics (since its so dissapative).   

This looks good to me!

File: SU2_CFD/src/solvers/CNSSolver.cpp [hunk 1]
```diff
@@ -110,7 +110,7 @@ void CNSSolver::Preprocessing(CGeometry *geometry, CSolver **solver_container, C
   CommonPreprocessing(geometry, solver_container, config, iMesh, iRKStep, RunTime_EqSystem, Output);
 
   /*--- Compute gradient for MUSCL reconstruction, for output (i.e. the
-   turbulence solver) only density and velocity are needed ---*/
+   turbulence solver, and post) only temperature and velocity are needed ---*/
```
Comment (WallyMaier) [inline SU2_CFD/src/solvers/CNSSolver.cpp:113]: Is post referring to post-processing?

Comment (pcarruscag) [reply SU2_CFD/src/solvers/CNSSolver.cpp:113]: yes, I did not write "processing" because the 2 lines lined up with just post
