### PR TITLE
Wrap MPI_Allgatherv for NdFlattener

### LINKED ISSUE #1893: Undefined behavior in NDFlatner causing spurious values of wall roughness
**Describe the bug**
I faced some non determinism in #1892 which I traced back to spurious values of walll roughness.
I tried running UB sanitizer and valgrind, the latter finds one memory error when accessing the flatner, but theres nothing while it's built.
The ndflatner unit test also fails on my machine, both in release and debug builds.

Given the complexity of that class, and it only being used in one place, I just wrote alternative code.
@maxaehle can you investigate the issue?

**Desktop (please complete the following information):**
 - ubuntu 22 + gcc + mpich (standard packages)

### PR DESCRIPTION
**Pull request by maxaehle**
## Proposed Changes
Let NdFlattener use a wrapped [MPI_Allgatherv](https://www.mpich.org/static/docs/v3.2/www3/MPI_Allgatherv.html) function which checks the number of participating MPI ranks. If there is only one, perform a simple copy operation instead.

I hope that this fixes #1893, which I believe to be the result of a bug in MPICH. In my Ubuntu MPICH container, the `[NdFlattener]` test succeeds with these changes. 

## Related Work
#1893 

## PR Checklist
*Put an X by all that apply. You can fill this out after submitting the PR. If you have any questions, don't hesitate to ask! We want to help. These are a guide for you to know what the reviewers will be looking for in your contribution.*

- [X] I am submitting my contribution to the develop branch.
- [ ] My contribution generates no new compiler warnings (try with --warnlevel=3 when using meson).
- [ ] My contribution is commented and consistent with SU2 style (https://su2code.github.io/docs_v7/Style-Guide/).
- [ ] I have added a test case that demonstrates my contribution, if necessary.
- [ ] I have updated appropriate documentation (Tutorials, Docs Page, config_template.cpp), if necessary.

### CODE REVIEW

File: Common/include/toolboxes/ndflattener.hpp [hunk 1]
```diff
@@ -207,6 +207,20 @@
...
 
+/*! Allgatherv wrapper defaulting to a copy operation if there is only a single MPI rank.
+ *
+ *  Introducing this was necessary because MPICH's Allgatherv behaved unexpectedly if there
+ *  is only one MPI rank.
+ */
+static inline void SU2_MPI_Allgatherv_safe(const void* sendbuf, int sendcount, SU2_MPI::Datatype sendtype, void* recvbuf,
+                              const int* recvcounts, const int* displs, SU2_MPI::Datatype recvtype, SU2_MPI::Comm comm) {
+  if(SU2_MPI::GetSize()==1){
+    SU2_MPI::CopyData(sendbuf,recvbuf,sendcount,sendtype,displs[0]);
```
Comment (pcarruscag) [inline Common/include/toolboxes/ndflattener.hpp:218]:
```suggestion
 *  is only one MPI rank (seemingly ignoring displs[0] != 0).
 */
static inline void SU2_MPI_Allgatherv_safe(const void* sendbuf, int sendcount, SU2_MPI::Datatype sendtype, void* recvbuf,
                              const int* recvcounts, const int* displs, SU2_MPI::Datatype recvtype, SU2_MPI::Comm comm) {
  if (SU2_MPI::GetSize() == 1) {
    SU2_MPI::CopyData(sendbuf, recvbuf, sendcount, sendtype, displs[0]);
```

**Review by pcarruscag — APPROVED** [review]
Thanks
